name: Tambahkan Issue Baru ke Project

on:
  issues:
    types: [opened]  # Trigger hanya saat issue baru dibuat

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Tambahkan ke Project GitHub
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/users/birrulwldain/projects/5
        github-token: ${{ secrets.GH_TOKEN }}
