name: Tambahkan Issue ke GitHub Project

on:
  issues:
    types: [opened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Tambah Issue ke Project V2
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/birrulwldain/projects/1
          github-token: ${{ secrets.GH_TOKEN }}
