name: Add New Issues to GitHub Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const projectId = "PVT_kwHOAvc3Js4A2O94"; // ID Project kamu
            const issueUrl = context.payload.issue.html_url;

            await github.request('POST /projects/v2/projects/{project_id}/items', {
              project_id: projectId,
              content_type: "Issue",
              content_url: issueUrl,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
